In [39]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [40]:
df = pd.read_csv("Heart.csv")

In [41]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [42]:
df.shape

(303, 15)

In [43]:
df1=df.drop(["Unnamed: 0"],axis=1)
df1

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [44]:
df.isnull()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [45]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [46]:
df.dtypes

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [47]:
print(df==0)

     Unnamed: 0    Age    Sex  ChestPain  RestBP   Chol    Fbs  RestECG  \
0         False  False  False      False   False  False  False    False
1         False  False  False      False   False  False   True    False
2         False  False  False      False   False  False   True    False
3         False  False  False      False   False  False   True     True
4         False  False   True      False   False  False   True    False
..          ...    ...    ...        ...     ...    ...    ...      ...
298       False  False  False      False   False  False   True     True
299       False  False  False      False   False  False  False     True
300       False  False  False      False   False  False   True     True
301       False  False   True      False   False  False   True    False
302       False  False  False      False   False  False   True     True

     MaxHR  ExAng  Oldpeak  Slope     Ca   Thal    AHD
0    False   True    False  False   True  False  False
1    False  False    False  False  False  False  False
2    False  False    False  False  False  False  False
3    False   True    False  False   True  False  False
4    False   True    False  False   True  False  False
..     ...    ...      ...    ...    ...    ...    ...
298  False   True    False  False   True  False  False
299  False   True    False  False  False  False  False
300  False  False    False  False  False  False  False
301  False   True     True  False  False  False  False
302  False   True     True  False  False  False  False

[303 rows x 15 columns]

In [48]:
(df==0).sum(axis=1)

0      2
1      1
2      1
3      4
4      4
      ..
298    4
299    2
300    2
301    4
302    4
Length: 303, dtype: int64

In [49]:
(df==0).sum(axis=0)

Unnamed: 0      0
Age             0
Sex            97
ChestPain       0
RestBP          0
Chol            0
Fbs           258
RestECG       151
MaxHR           0
ExAng         204
Oldpeak        99
Slope           0
Ca            176
Thal            0
AHD             0
dtype: int64

In [50]:
df["Age"].mean()

54.43894389438944

In [51]:
df2=df1.sample(frac=0.75)
df2

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
155,70,1,asymptomatic,130,322,0,2,109,0,2.4,2,3.0,normal,Yes
180,48,1,asymptomatic,124,274,0,2,166,0,0.5,2,0.0,reversable,Yes
289,56,1,nontypical,120,240,0,0,169,0,0.0,3,0.0,normal,No
99,48,1,asymptomatic,122,222,0,2,186,0,0.0,1,0.0,normal,No
53,44,1,nontypical,130,219,0,2,188,0,0.0,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,54,1,nonanginal,125,273,0,2,152,0,0.5,3,1.0,normal,No
22,58,1,nontypical,120,284,0,2,160,0,1.8,2,0.0,normal,Yes
134,43,0,nonanginal,122,213,0,0,165,0,0.2,2,0.0,normal,No
24,60,1,asymptomatic,130,206,0,2,132,1,2.4,2,2.0,reversable,Yes
130,54,1,nonanginal,120,258,0,2,147,0,0.4,2,0.0,reversable,No

In [52]:
df3=df1.sample(frac=0.25)
df3

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
204,43,1,asymptomatic,110,211,0,0,161,0,0.0,1,0.0,reversable,No
136,70,1,asymptomatic,145,174,0,0,125,1,2.6,3,0.0,reversable,Yes
236,56,1,asymptomatic,130,283,1,2,103,1,1.6,3,0.0,reversable,Yes
49,53,1,nonanginal,130,197,1,2,152,0,1.2,3,0.0,normal,No
275,64,1,typical,170,227,0,2,155,0,0.6,2,0.0,reversable,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
99,48,1,asymptomatic,122,222,0,2,186,0,0.0,1,0.0,normal,No
169,45,0,nontypical,112,160,0,0,138,0,0.0,2,0.0,normal,No
186,42,1,nonanginal,120,240,1,0,194,0,0.8,3,0.0,reversable,No
11,56,0,nontypical,140,294,0,2,153,0,1.3,2,0.0,normal,No

In [53]:
subdata=df1[['Age','Sex','ChestPain','RestBP','Chol']]

In [54]:
subdata

     Age  Sex     ChestPain  RestBP  Chol
0     63    1       typical     145   233
1     67    1  asymptomatic     160   286
2     67    1  asymptomatic     120   229
3     37    1    nonanginal     130   250
4     41    0    nontypical     130   204
..   ...  ...           ...     ...   ...
298   45    1       typical     110   264
299   68    1  asymptomatic     144   193
300   57    1  asymptomatic     130   131
301   57    0    nontypical     130   236
302   38    1    nonanginal     138   175

[303 rows x 5 columns]

In [55]:
sub_data1 = subdata.sample(frac= 0.75)
sub_data1.count()

Age          227
Sex          227
ChestPain    227
RestBP       227
Chol         227
dtype: int64

In [56]:
sub_data1 = subdata.sample(frac= 0.25)
sub_data1.count()

Age          76
Sex          76
ChestPain    76
RestBP       76
Chol         76
dtype: int64

In [71]:
x=df.drop(columns="AHD")
y=df["AHD"]

In [72]:
(x_train,x_test,y_train,y_test)=train_test_split(x,y,train_size=0.8)

In [73]:
x_train

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
63,54,0,nonanginal,135,304,1,0,170,0,0.0,1,0.0,normal
258,70,1,nontypical,156,245,0,2,143,0,0.0,1,0.0,normal
231,55,0,asymptomatic,180,327,0,1,117,1,3.4,2,0.0,normal
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable
262,60,0,typical,150,240,0,0,171,0,0.9,1,0.0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,50,0,nonanginal,120,219,0,0,158,0,1.6,2,0.0,normal
165,57,1,asymptomatic,132,207,0,0,168,1,0.0,1,0.0,reversable
55,54,1,asymptomatic,124,266,0,2,109,1,2.2,2,1.0,reversable
226,47,1,asymptomatic,112,204,0,0,143,0,0.1,1,0.0,normal
88,53,0,asymptomatic,138,234,0,2,160,0,0.0,1,0.0,normal

In [74]:
x_test

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
257,76,0,nonanginal,140,197,0,1,116,0,1.1,2,0.0,normal
161,77,1,asymptomatic,125,304,0,2,162,1,0.0,1,3.0,normal
153,55,1,asymptomatic,160,289,0,2,145,1,0.8,2,1.0,reversable
230,52,0,nonanginal,136,196,0,2,169,0,0.1,2,0.0,normal
43,59,1,nonanginal,150,212,1,0,157,0,1.6,1,0.0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,69,0,typical,140,239,0,0,151,0,1.8,1,2.0,normal
259,57,1,nontypical,124,261,0,0,141,0,0.3,1,0.0,reversable
85,44,1,nonanginal,140,235,0,2,180,0,0.0,1,0.0,normal
70,65,0,nonanginal,155,269,0,0,148,0,0.8,1,0.0,normal
96,59,1,asymptomatic,110,239,0,2,142,1,1.2,2,1.0,reversable

In [67]:
y_train

21      No
241     No
161    Yes
232    Yes
148     No
      ...
123    Yes
62     Yes
293    Yes
70      No
112     No
Name: AHD, Length: 242, dtype: object

In [68]:
y_test

45     Yes
52     Yes
199    Yes
294    Yes
129     No
      ...
18      No
189    Yes
71     Yes
226     No
179     No
Name: AHD, Length: 61, dtype: object

In [70]:
data= df1.replace(to_replace=["Yes","No"],value = [0,1])
data

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,1
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,0
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,0
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,1
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,0
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,0
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,0
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,0
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,1